apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  annotations:
    ignore-check.kube-linter.io/latest-tag: "image is built directly into the minikube docker daemon, imagePullPolicy is Never"
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: fibonacci-worker
        image: fibonacci-worker:latest
        command: ["node", "dist/worker/index.js"]
        imagePullPolicy: Never
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000        # "node" user from the node:25-alpine image
          readOnlyRootFilesystem: true
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        env:
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: redis-url
        - name: RABBIT_URL
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: rabbitmq-url
# no need to have a service for the worker, because it works with rabbitmq and redis directly