name: CI Tests

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci
      
      - name: Run audit
        run: npm audit --audit-level=high

      - name: Run build
        run: npm run build

      - name: Run lint
        run: npm run lint

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Run validation for branch name
        run: npx validate-branch-name -t ${{ steps.extract_branch.outputs.branch }}

      - name: Run test
        run: npm run test:coverage:report

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: "./coverage"

      - name: Run security scan (bearer cli)
        uses: bearer/bearer-action@v2
        with:
          severity: critical,high,medium

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag fibonacci-test:${{ github.sha }}

      - name: Run Trivy container scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'fibonacci-test:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          timeout: 10m0s

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  deploy-docs:
    needs: build
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    concurrency: 
      group: 'deploy-docs-concurrency-group'
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download coverage report from previous job
        uses: actions/download-artifact@v5
        with:
          name: coverage-report
          path: "./docs/coverage"

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with: 
          path: "./docs"

      - name: Deploy docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
