name: CI Tests

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci
      
      - name: Run audit
        run: npm audit --audit-level=high

      - name: Run build
        run: npm run build

      - name: Run lint
        run: npm run lint

      - name: Run linter for branch name
        run: npm run lint:branch

      - name: Run test
        run: npm test
      
      - name: Run security scan (bearer cli)
        uses: bearer/bearer-action@v2
        with:
          severity: critical,high,medium

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag fibonacci-test:$(date +%s)

  deploy-docs:
    needs: build
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    concurrency: 
      group: 'deploy-docs-concurrency-group'
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with: 
          path: "./docs"

      - name: Deploy docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
